name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Free space before maximization
        run: |
          echo "Free space:"
          df -h | grep -v tmpfs
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Free space after maximization
        run: |
          echo "Free space:"
          df -h | grep -v tmpfs
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List memory capacity 
        run: |
          free -m
      - name: List processor capacity 
        run: |
          cat /proc/cpuinfo
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: List git files in the repository recursively
        run: |
          find ${{ github.workspace }}/.git* -type f | sort
      - name: Create large file in the work space
        run: |
          dd if=/dev/zero of=${{ github.workspace }}/junkfile bs=1G count=114
          df -h ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
